### ISSUE TITLE
TNT Sports replacing BT Sports for UK

### ISSUE THREAD

**Issue by mraniki** [fraudiay79/logos#3]
TNT Sports 
https://img01.products.bt.co.uk/content/dam/bt/portal/images/logos/tnt/TNTSports1_Logo_White_RGB_Logo.png
https://img01.products.bt.co.uk/content/dam/bt/portal/images/logos/tnt/TNTSports2_Logo_White_RGB_Logo.png
https://img01.products.bt.co.uk/content/dam/bt/portal/images/logos/tnt/TNTSports3_Logo_White_RGB_Logo.png
https://img01.products.bt.co.uk/content/dam/bt/portal/images/logos/tnt/TNTSports4_Logo_White_RGB_Logo.png

https://www.bt.com/sport/features/what-does-the-switch-to-tnt-sports-mean-for-bt-sport-customers

**Comment by fraudiay79** [comment]
TNT sports logos have been added to UK folder
